project:
  type: book

book:
  title: "Investigating periodic and 1/f  features of electromagnetic neuroimaging data and their mapping to physiology and cognition"
  author: "Daniel Borek"
  chapters:
    - index.qmd
    - chapters/ch02.qmd


format:
  typst:
    fontsize: 12pt
    number-sections: true
    toc: true
    toc-depth: 2
    # Tell Quarto/Pandoc to wrap citations in hyperlinks
    link-citations: true
    # Tell Typst to color all links blue
    include-in-header:
      - text: |
          #show link: set text(fill: rgb("0000FF"))

  docx:
    toc: true
    toc-depth: 3
    toc-title: "Contents"

bibliography:
  - references.bib
reference-section-title: References
citeproc: true
suppress-bibliography: false